targets:
  $default:
    sources:
      - lib/**
      - test/**
      - "tool/**"
    builders:
      drift_dev:
        enabled: true
        options: &options
          generate_connect_constructor: false
          scoped_dart_components: true
